name: CI Build Check

on:
  schedule:
    - cron: "0 */6 * * *"   # Every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        run: echo "Preparing build environment for ${{ matrix.os }}..."

      - name: Dummy Build Process
        run: |
          echo "Building project for ${{ matrix.os }}..."
          echo "✅ Build successful for ${{ matrix.os }}!"

      - name: Archive Build Logs
        run: |
          mkdir -p logs
          echo "$(date) - Build Completed for ${{ matrix.os }}" > logs/build-${{ matrix.os }}.log

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}
          path: logs/build-${{ matrix.os }}.log
