name: Heartbeat Commit

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p logs
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"
          echo "$(date) - heartbeat ping" >> logs/heartbeat.txt
          git add logs/heartbeat.txt
          git commit -m "heartbeat: ping" || echo "No changes"
          git push
