name: Heartbeat Commit

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Git User
        run: |
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Heartbeat Commit
        run: |
          mkdir -p logs
          echo "$(date) - heartbeat ping" >> logs/heartbeat.log
          git add logs/heartbeat.log
          git commit -m "chore: heartbeat ping" || echo "No changes to commit"
          git push origin main
