name: Heartbeat Commit
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"
          date > heartbeat.txt
          git add heartbeat.txt
          git commit -m "chore: heartbeat sync $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
