name: Heartbeat Commit

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Heartbeat Log
        run: |
          mkdir -p logs
          echo "$(date) - Heartbeat OK" >> logs/heartbeat.log
      - uses: actions/upload-artifact@v4
        with:
          name: heartbeat-logs
          path: logs/

