name: Random Commit

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  random_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Generate Random Commit Message
        run: |
          MESSAGES=("chore: sync Pharos test" "update: log status" "fix: heartbeat patch" "docs: refresh logs" "test: workflow activity" "refactor: optimize commit")
          MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          echo "$(date) - $MSG" >> activity-log.txt
          git add activity-log.txt
          git commit -m "$MSG" || echo "No changes to commit"

      - name: Push Commit
        run: git push origin main
