name: Random Commit

on:
  schedule:
    - cron: "15 */8 * * *"  # Every 8 hours (offset 15 mins)
  workflow_dispatch:

jobs:
  random-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Random Commit Simulation
        run: |
          mkdir -p logs
          echo "$(date) - Random Commit Executed" >> logs/random-commit.log
      - uses: actions/upload-artifact@v4
        with:
          name: random-commit-logs
          path: logs/

