name: Random Commit

on:
  schedule:
    - cron: "15 */8 * * *"   # every 8 hours
  workflow_dispatch:

jobs:
  random_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p logs
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"
          MSGS=("feat: cosmic commit" "chore: star drift" "update: galaxy pulse" "refactor: moonlight logs")
          MSG=${MSGS[$RANDOM % ${#MSGS[@]}]}
          echo "$(date) - $MSG" >> logs/random-commit.txt
          git add logs/random-commit.txt
          git commit -m "$MSG" || echo "No changes"
          git push

